//-----------------------------------------------------------------------------------
// Description: Transaction object used throughout the UVM environment.
//
// Purpose:
// - Carries stimulus from sequences to the driver.
// - Captures DUT activity through the monitor.
// - Acts as the common data object shared between:
//      • Sequencer
//      • Driver
//      • Monitor
//      • Scoreboard
//      • Subscriber
//
// Notes:
// - Input fields are randomized by sequences.
// - Output fields are populated by the monitor.
// - Constraints are biased toward normal FIFO traffic while
//   still allowing reset and corner-case scenarios.
//
//-----------------------------------------------------------------------------------

class sequence_item extends uvm_sequence_item;

    //////////////////////////////////////////////////////////
    // Factory Registration
    //
    // Enables automation for:
    // - print()
    // - copy()
    // - compare()
    // - pack/unpack
    // - factory overrides
    //////////////////////////////////////////////////////////

    `uvm_object_utils_begin(sequence_item)

        `uvm_field_int(i_w_rstn_tb , UVM_ALL_ON)
        `uvm_field_int(i_w_inc_tb  , UVM_ALL_ON)

        `uvm_field_int(i_r_rstn_tb , UVM_ALL_ON)
        `uvm_field_int(i_r_inc_tb  , UVM_ALL_ON)

        `uvm_field_int(i_w_data_tb , UVM_ALL_ON)

        `uvm_field_int(o_r_data_tb , UVM_ALL_ON)
        `uvm_field_int(o_empty_tb  , UVM_ALL_ON)
        `uvm_field_int(o_full_tb   , UVM_ALL_ON)

    `uvm_object_utils_end

    //////////////////////////////////////////////////////////
    // Randomized Stimulus Fields
    //
    // Generated by sequences and consumed by the driver.
    //////////////////////////////////////////////////////////

    rand bit          i_w_rstn_tb;
    rand bit          i_w_inc_tb;

    rand bit          i_r_rstn_tb;
    rand bit          i_r_inc_tb;

    rand bit [15:0]   i_w_data_tb;

    //////////////////////////////////////////////////////////////////////////////
    // Observed DUT Fields
    //
    // Populated by the monitor and used by the scoreboard and coverage collector.
    //////////////////////////////////////////////////////////////////////////////

    bit [15:0]        o_r_data_tb;

    bit               o_empty_tb;
    bit               o_full_tb;

    //////////////////////////////////////////////////////////
    // Traffic Constraints
    //
    // Bias stimulus toward active FIFO operation while
    // preserving occasional idle cycles.
    //////////////////////////////////////////////////////////

    constraint c_enable_distribution {
        i_w_inc_tb dist {1 := 95, 0 := 5};
        i_r_inc_tb dist {1 := 95, 0 := 5};}

    //////////////////////////////////////////////////////////
    // Reset Constraints
    //
    // Keep resets inactive most of the time so normal FIFO
    // functionality dominates regression execution.
    //////////////////////////////////////////////////////////

    constraint c_reset_distribution {
        i_w_rstn_tb dist {1 := 98, 0 := 2};
        i_r_rstn_tb dist {1 := 98, 0 := 2}; }

    //////////////////////////////////////////////////////////
    // Reset Coordination
    //
    // Soft constraints reduce simultaneous reset activity
    // while allowing dedicated reset sequences to override
    // the behavior when required.
    //////////////////////////////////////////////////////////

    constraint c_reset_behavior{
        soft (i_w_rstn_tb == 0) -> (i_r_rstn_tb == 1);
        soft (i_r_rstn_tb == 0) -> (i_w_rstn_tb == 1);  }

    //////////////////////////////////////////////////////////
    // Constructor
    //////////////////////////////////////////////////////////

    function new(string name = "sequence_item");
        super.new(name);
    endfunction

    ///////////////////////////////////////////////////////////////////////////////
    // Debug Utility
    //
    // Displays complete transaction contents for debugging and regression analysis.
    ////////////////////////////////////////////////////////////////////////////////

    function void display_sequence_item (
        input string name = "SEQUENCE_ITEM" );

        $display("\n************************************************");
        $display("        %0s", name);
        $display("************************************************");

        $display("i_w_rstn_tb = %0d", i_w_rstn_tb);
        $display("i_w_inc_tb  = %0d", i_w_inc_tb);

        $display("i_r_rstn_tb = %0d", i_r_rstn_tb);
        $display("i_r_inc_tb  = %0d", i_r_inc_tb);

        $display("i_w_data_tb = %0h", i_w_data_tb);

        $display("o_r_data_tb = %0h", o_r_data_tb);

        $display("o_empty_tb  = %0d", o_empty_tb);
        $display("o_full_tb   = %0d", o_full_tb);

        $display("************************************************\n");

    endfunction

endclass

//////////////////////////////////////////////////////////////////////////////////
